// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Brand Color documents
 */
interface BrandColorDocumentData {
  /**
   * Color field in *Brand Color*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_color.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * Preview Image field in *Brand Color*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_color.preview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  preview_image: prismic.ImageField<never>;
}

/**
 * Brand Color document from Prismic
 *
 * - **API ID**: `brand_color`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandColorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BrandColorDocumentData>,
    "brand_color",
    Lang
  >;

/**
 * Content for Button Style documents
 */
interface ButtonStyleDocumentData {
  /**
   * Primary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.primary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Secondary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.secondary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Hover Primary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.hover_primary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hover_primary_color: prismic.ContentRelationshipField;

  /**
   * Hover Secondary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.hover_secondary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hover_secondary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Disabled Primary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.disabled_primary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  disabled_primary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Disabled Secondary Color field in *Button Style*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.disabled_secondary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  disabled_secondary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Type field in *Button Style*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Filled
   * - **API ID Path**: button_style.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Filled" | "Outlined", "filled">;

  /**
   * Full Width field in *Button Style*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: button_style.full_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;

  /**
   * Preview Image field in *Button Style*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: button_style.preview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  preview_image: prismic.ImageField<never>;
}

/**
 * Button Style document from Prismic
 *
 * - **API ID**: `button_style`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonStyleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ButtonStyleDocumentData>,
    "button_style",
    Lang
  >;

/**
 * Item in *Footer Section → Links*
 */
export interface FooterSectionDocumentDataLinksItem {
  /**
   * Link field in *Footer Section → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer Section documents
 */
interface FooterSectionDocumentData {
  /**
   * Title field in *Footer Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Links field in *Footer Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterSectionDocumentDataLinksItem>>;
}

/**
 * Footer Section document from Prismic
 *
 * - **API ID**: `footer_section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FooterSectionDocumentData>,
    "footer_section",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = CardsSection1Slice | HeroSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Content for Mega Menu Featured Image documents
 */
interface MegaMenuFeaturedImageDocumentData {
  /**
   * Image field in *Mega Menu Featured Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_featured_image.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Mega Menu Featured Image*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_featured_image.caption
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * Link field in *Mega Menu Featured Image*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_featured_image.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Hover Text field in *Mega Menu Featured Image*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_featured_image.hover_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hover_text: prismic.KeyTextField;
}

/**
 * Mega Menu Featured Image document from Prismic
 *
 * - **API ID**: `mega_menu_featured_image`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MegaMenuFeaturedImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MegaMenuFeaturedImageDocumentData>,
    "mega_menu_featured_image",
    Lang
  >;

/**
 * Item in *Mega Menu Item → Sections*
 */
export interface MegaMenuItemDocumentDataSectionsItem {
  /**
   * Section field in *Mega Menu Item → Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.sections[].section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"mega_menu_section">;
}

/**
 * Item in *Mega Menu Item → Featured Images*
 */
export interface MegaMenuItemDocumentDataFeaturedImagesItem {
  /**
   * Featured Image field in *Mega Menu Item → Featured Images*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.featured_images[].featured_image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_image: prismic.ContentRelationshipField<"mega_menu_featured_image">;
}

/**
 * Content for Mega Menu Item documents
 */
interface MegaMenuItemDocumentData {
  /**
   * Label field in *Mega Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * URL field in *Mega Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Sections field in *Mega Menu Item*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<Simplify<MegaMenuItemDocumentDataSectionsItem>>;

  /**
   * Featured Images field in *Mega Menu Item*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_item.featured_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_images: prismic.GroupField<
    Simplify<MegaMenuItemDocumentDataFeaturedImagesItem>
  >;
}

/**
 * Mega Menu Item document from Prismic
 *
 * - **API ID**: `mega_menu_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MegaMenuItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MegaMenuItemDocumentData>,
    "mega_menu_item",
    Lang
  >;

/**
 * Item in *Mega Menu Section → Links*
 */
export interface MegaMenuSectionDocumentDataLinksItem {
  /**
   * Link field in *Mega Menu Section → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_section.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Mega Menu Section documents
 */
interface MegaMenuSectionDocumentData {
  /**
   * Title field in *Mega Menu Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_section.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Links field in *Mega Menu Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu_section.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<MegaMenuSectionDocumentDataLinksItem>>;
}

/**
 * Mega Menu Section document from Prismic
 *
 * - **API ID**: `mega_menu_section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MegaMenuSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MegaMenuSectionDocumentData>,
    "mega_menu_section",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Mega Menu Item field in *Settings → Navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].mega_menu_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mega_menu_item: prismic.ContentRelationshipField<"mega_menu_item">;
}

/**
 * Item in *Settings → Footer Sections*
 */
export interface SettingsDocumentDataFooterSectionsItem {
  /**
   * Section field in *Settings → Footer Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_sections[].section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"footer_section">;
}

/**
 * Item in *Settings → Footer Icon Links*
 */
export interface SettingsDocumentDataFooterIconLinksItem {
  /**
   * Link field in *Settings → Footer Icon Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Name field in *Settings → Footer Icon Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon_links[].link_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Icon field in *Settings → Footer Icon Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Logo Main Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_main_image: prismic.ImageField<never>;

  /**
   * Logo Text Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_text_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_text_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Special Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.special_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  special_link: prismic.LinkField;

  /**
   * Footer Sections field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_sections: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSectionsItem>
  >;

  /**
   * Footer Icon Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_icon_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterIconLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type StandardPageDocumentDataSlicesSlice = CardsSection1Slice | HeroSlice;

/**
 * Content for Standard Page documents
 */
interface StandardPageDocumentData {
  /**
   * Slice Zone field in *Standard Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StandardPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Standard Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: standard_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Standard Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: standard_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Standard Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Standard Page document from Prismic
 *
 * - **API ID**: `standard_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StandardPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<StandardPageDocumentData>,
    "standard_page",
    Lang
  >;

export type AllDocumentTypes =
  | BrandColorDocument
  | ButtonStyleDocument
  | FooterSectionDocument
  | HomePageDocument
  | MegaMenuFeaturedImageDocument
  | MegaMenuItemDocument
  | MegaMenuSectionDocument
  | SettingsDocument
  | StandardPageDocument;

/**
 * Item in *CardsSection1 → Default → Primary → Cards*
 */
export interface CardsSection1SliceDefaultPrimaryCardsItem {
  /**
   * Image field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * Button Primary Color field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].button_primary_color
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_primary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Button Secondary Color field in *CardsSection1 → Default → Primary → Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[].button_secondary_color
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_secondary_color: prismic.ContentRelationshipField<"brand_color">;
}

/**
 * Primary content in *CardsSection1 → Default → Primary*
 */
export interface CardsSection1SliceDefaultPrimary {
  /**
   * Cards field in *CardsSection1 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section1.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<CardsSection1SliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for CardsSection1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSection1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSection1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardsSection1*
 */
type CardsSection1SliceVariation = CardsSection1SliceDefault;

/**
 * CardsSection1 Shared Slice
 *
 * - **API ID**: `cards_section1`
 * - **Description**: CardsSection1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSection1Slice = prismic.SharedSlice<
  "cards_section1",
  CardsSection1SliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Primary Color field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].primary_color
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_color: prismic.ContentRelationshipField<"brand_color">;

  /**
   * Secondary Color field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].secondary_color
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_color: prismic.ContentRelationshipField<"brand_color">;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subtext field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BrandColorDocument,
      BrandColorDocumentData,
      ButtonStyleDocument,
      ButtonStyleDocumentData,
      FooterSectionDocument,
      FooterSectionDocumentData,
      FooterSectionDocumentDataLinksItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      MegaMenuFeaturedImageDocument,
      MegaMenuFeaturedImageDocumentData,
      MegaMenuItemDocument,
      MegaMenuItemDocumentData,
      MegaMenuItemDocumentDataSectionsItem,
      MegaMenuItemDocumentDataFeaturedImagesItem,
      MegaMenuSectionDocument,
      MegaMenuSectionDocumentData,
      MegaMenuSectionDocumentDataLinksItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterSectionsItem,
      SettingsDocumentDataFooterIconLinksItem,
      StandardPageDocument,
      StandardPageDocumentData,
      StandardPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardsSection1Slice,
      CardsSection1SliceDefaultPrimaryCardsItem,
      CardsSection1SliceDefaultPrimary,
      CardsSection1SliceVariation,
      CardsSection1SliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
