// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  cards_section1: dynamic(() => import("./CardsSection1")),
  carousel_reviews: dynamic(() => import("./CarouselReviews")),
  content_cards: dynamic(() => import("./ContentCards")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
  single_review: dynamic(() => import("./SingleReview")),
  social_links: dynamic(() => import("./SocialLinks")),
  standard_section1: dynamic(() => import("./StandardSection1")),
  standard_section2: dynamic(() => import("./StandardSection2")),
  text_with_heading: dynamic(() => import("./TextWithHeading")),
  three_image_section: dynamic(() => import("./ThreeImageSection")),
  value_chain: dynamic(() => import("./ValueChain")),
  video: dynamic(() => import("./Video")),
  video_cards: dynamic(() => import("./VideoCards")),
};
