// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cards_section1: dynamic(() => import("./CardsSection1")),
  carousel_reviews: dynamic(() => import("./CarouselReviews")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
  single_review: dynamic(() => import("./SingleReview")),
  standard_section1: dynamic(() => import("./StandardSection1")),
  standard_section2: dynamic(() => import("./StandardSection2")),
  text_with_heading: dynamic(() => import("./TextWithHeading")),
  video: dynamic(() => import("./Video")),
};
